### ISSUE TITLE
DialogWindow 应该如何 ShowDialog?

### ISSUE THREAD

**Issue by shinywong** [ZhengDaoWang/PrismMetroSample#1]
你好，

代码中似乎只有 AlertDialog, SuccessDialog 和 WarningDialog 这三个 IDialogAware 的 ShowDialog 方式，
没有 DialogWindow (IDialogWindow) 的 ShowDialog。

我（在我自己的工程中）写了如下代码：

`_dialogService.ShowDialog("DialogWindow", null, null);`

报如下异常：

`DryIoc.ContainerException: 'Implementation type is not specified when using automatic constructor selection: Object {ServiceKey="DialogWindow", DryIoc.IfUnresolved.ReturnDefault} FactoryId=51 IsResolutionCall
  from Container without Scope
 with Rules with {AutoConcreteTypeResolution}
 with Made={FactoryMethod=ConstructorWithResolvableArguments}'`

请教一下 IDialogWindow 应该如何调用 ShowDialog? 非常感谢。

**Comment by ZhengDaoWang** [comment]
> 你好，
> 
> 代码中似乎只有 AlertDialog, SuccessDialog 和 WarningDialog 这三个 IDialogAware 的 ShowDialog 方式，
> 没有 DialogWindow (IDialogWindow) 的 ShowDialog。
> 
> 我（在我自己的工程中）写了如下代码：
> 
> `_dialogService.ShowDialog("DialogWindow", null, null);`
> 
> 报如下异常：
> 
> `DryIoc.ContainerException: 'Implementation type is not specified when using automatic constructor selection: Object {ServiceKey="DialogWindow", DryIoc.IfUnresolved.ReturnDefault} FactoryId=51 IsResolutionCall from Container without Scope with Rules with {AutoConcreteTypeResolution} with Made={FactoryMethod=ConstructorWithResolvableArguments}'`
> 
> 请教一下 IDialogWindow 应该如何调用 ShowDialog? 非常感谢。

step1：
在App.cs文件下：
 protected override void RegisterTypes(IContainerRegistry containerRegistry)
{
       containerRegistry.RegisterDialogWindow<DialogWindow>();
}
step 2:
在你所在的ViewModel构造函数初始化IDialogService，并且调用IDialogService.ShowDialog("DialogWindow", null, null);

但是我发现在单独这样调用的情况会发生以下报错：System.NullReferenceException:“A dialog's content must be a FrameworkElement”

貌似这是目前的一个bug，也就是目前只能通过IDialogService调用IDialogAware ，IDialogWindow接口只是作为IDialogAware控件的窗体承载，负责统一修改IDialogAware的窗体样式

**Comment by ZhengDaoWang** [comment]
> 你好，
> 
> 代码中似乎只有 AlertDialog, SuccessDialog 和 WarningDialog 这三个 IDialogAware 的 ShowDialog 方式，
> 没有 DialogWindow (IDialogWindow) 的 ShowDialog。
> 
> 我（在我自己的工程中）写了如下代码：
> 
> `_dialogService.ShowDialog("DialogWindow", null, null);`
> 
> 报如下异常：
> 
> `DryIoc.ContainerException: 'Implementation type is not specified when using automatic constructor selection: Object {ServiceKey="DialogWindow", DryIoc.IfUnresolved.ReturnDefault} FactoryId=51 IsResolutionCall from Container without Scope with Rules with {AutoConcreteTypeResolution} with Made={FactoryMethod=ConstructorWithResolvableArguments}'`
> 
> 请教一下 IDialogWindow 应该如何调用 ShowDialog? 非常感谢。

再补充以下，通过查看Prism的源码证实了我以上观点，其实应该不算bug，就是IDialogService.Show or IDialogService.ShowDialog的第一个参数name，只能为注入到容器的IDialogAware

**Comment by shinywong** [comment]
非常感谢，看来只能用 IDialogAware 了。
