### ISSUE TITLE
您好！编译时候有报警，我想运行起来，学习下，谢谢！

### ISSUE THREAD

**Issue by lb123456789** [ZhengDaoWang/PrismMetroSample#2]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0006	未能找到元数据文件“C:\Users\Administrator\Downloads\PrismMetroSample-NET5-Prism8.0\PrismMetroSample-NET5-Prism8.0\PrismMetroSample\PrismMetroSample\PrismMetroSample.Styling\bin\Debug\net5.0-windows\PrismMetroSample.Styling.dll”	PrismMetroSample.Shell	C:\Users\Administrator\Downloads\PrismMetroSample-NET5-Prism8.0\PrismMetroSample-NET5-Prism8.0\PrismMetroSample\PrismMetroSample\PrismMetroSample.Shell\CSC	1	活动

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3491	未能向文件“obj\Debug\net5.0-windows\PrismMetroSample.Styling_yvfabvkk_wpftmp.GeneratedMSBuildEditorConfig.editorconfig”写入命令行。路径: obj\Debug\net5.0-windows\PrismMetroSample.Styling_yvfabvkk_wpftmp.GeneratedMSBuildEditorConfig.editorconfig 超过 OS 最大路径限制。完全限定的文件名必须少于 260 个字符。	PrismMetroSample.Styling	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.Managed.Core.targets	150

**Comment by ZhengDaoWang** [comment]
确认是否本地有安装.NET5的SDK？

> 严重性 代码 说明 项目 文件 行 禁止显示状态
> 错误 CS0006 未能找到元数据文件“C:\Users\Administrator\Downloads\PrismMetroSample-NET5-Prism8.0\PrismMetroSample-NET5-Prism8.0\PrismMetroSample\PrismMetroSample\PrismMetroSample.Styling\bin\Debug\net5.0-windows\PrismMetroSample.Styling.dll” PrismMetroSample.Shell C:\Users\Administrator\Downloads\PrismMetroSample-NET5-Prism8.0\PrismMetroSample-NET5-Prism8.0\PrismMetroSample\PrismMetroSample\PrismMetroSample.Shell\CSC 1 活动
> 
> 严重性 代码 说明 项目 文件 行 禁止显示状态
> 错误 MSB3491 未能向文件“obj\Debug\net5.0-windows\PrismMetroSample.Styling_yvfabvkk_wpftmp.GeneratedMSBuildEditorConfig.editorconfig”写入命令行。路径: obj\Debug\net5.0-windows\PrismMetroSample.Styling_yvfabvkk_wpftmp.GeneratedMSBuildEditorConfig.editorconfig 超过 OS 最大路径限制。完全限定的文件名必须少于 260 个字符。 PrismMetroSample.Styling C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.Managed.Core.targets 150

确认本地是否有安装.NET5的SDK？如安装了，可以先清理解决方案再重新生成下

**Comment by lb123456789** [comment]
安装了，版本如下

C:\Users\Administrator>dotnet --version
5.0.302

C:\Users\Administrator>

**Comment by lb123456789** [comment]
清理过了
